Fix e2e tests (#45)
* update chart + fix values

diff --git a/charts/blockscout-stack/values.yaml b/charts/blockscout-stack/values.yaml
--- a/charts/blockscout-stack/values.yaml
+++ b/charts/blockscout-stack/values.yaml
@@ -144,7 +144,9 @@ geth:
     tls:
       enabled: false
 
-  files: {}
+  files:
+    enabled: false
+    list: {}
 
   jwt:
     enabled: false
@@ -174,68 +176,70 @@ node:
     enabled: false
 
   files:
-    check-for-chaindata-berlin.sh: |-
-      #!/bin/sh
-      set -exu
+    enabled: false
+    list:
+      check-for-chaindata-berlin.sh: |-
+        #!/bin/sh
+        set -exu
 
-      echo running "${0}"
+        echo running "${0}"
 
-      GETH_DATA_DIR=/geth
-      GETH_CHAINDATA_DIR=$GETH_DATA_DIR/geth/chaindata
-      GETH_KEYSTORE_DIR=$GETH_DATA_DIR/keystore
+        GETH_DATA_DIR=/geth
+        GETH_CHAINDATA_DIR=$GETH_DATA_DIR/geth/chaindata
+        GETH_KEYSTORE_DIR=$GETH_DATA_DIR/keystore
 
-      if [ ! -d "$GETH_KEYSTORE_DIR" ]; then
-          echo "$GETH_KEYSTORE_DIR missing, running account import"
-          echo -n "$BLOCK_SIGNER_PRIVATE_KEY_PASSWORD" > "$GETH_DATA_DIR"/password
-          echo -n "$BLOCK_SIGNER_PRIVATE_KEY" > "$GETH_DATA_DIR"/block-signer-key
-          geth account import \
-              --datadir="$GETH_DATA_DIR" \
-              --password="$GETH_DATA_DIR"/password \
-              "$GETH_DATA_DIR"/block-signer-key
-          echo "get account import complete"
-      fi
+        if [ ! -d "$GETH_KEYSTORE_DIR" ]; then
+            echo "$GETH_KEYSTORE_DIR missing, running account import"
+            echo -n "$BLOCK_SIGNER_PRIVATE_KEY_PASSWORD" > "$GETH_DATA_DIR"/password
+            echo -n "$BLOCK_SIGNER_PRIVATE_KEY" > "$GETH_DATA_DIR"/block-signer-key
+            geth account import \
+                --datadir="$GETH_DATA_DIR" \
+                --password="$GETH_DATA_DIR"/password \
+                "$GETH_DATA_DIR"/block-signer-key
+            echo "get account import complete"
+        fi
 
-      if [ ! -d "$GETH_CHAINDATA_DIR" ]; then
-          echo "$GETH_CHAINDATA_DIR missing, running init"
-          geth init --datadir="$GETH_DATA_DIR" "$L2GETH_GENESIS_URL" "$L2GETH_GENESIS_HASH"
-          echo "geth init complete"
-      else
-          echo "$GETH_CHAINDATA_DIR exists, checking for hardfork."
-          echo "Chain config:"
-          geth dump-chain-cfg --datadir="$GETH_DATA_DIR"
-          if geth dump-chain-cfg --datadir="$GETH_DATA_DIR" | grep -q "\"berlinBlock\": $L2GETH_BERLIN_ACTIVATION_HEIGHT"; then
-              echo "Hardfork already activated."
-          else
-              echo "Hardfork not activated, running init."
-              geth init --datadir="$GETH_DATA_DIR" "$L2GETH_GENESIS_URL" "$L2GETH_GENESIS_HASH"
-              echo "geth hardfork activation complete"
-          fi
-      fi
-    l2geth-start.sh: |-
-      #!/bin/sh
-      set -eou
-      if [[ -z $DATADIR ]]; then
-          echo "Must pass DATADIR"
-          exit 1
-      fi
-      if [[ -z $BLOCK_SIGNER_ADDRESS ]]; then
-          echo "Must pass BLOCK_SIGNER_ADDRESS"
-          exit 1
-      fi
-      exec geth \
-        --vmodule=eth/*=5,miner=4,rpc=5,rollup=4,consensus/clique=1 \
-        --datadir=$DATADIR \
-        --password=$DATADIR/password \
-        --allow-insecure-unlock \
-        --unlock=$BLOCK_SIGNER_ADDRESS \
-        --mine \
-        --miner.etherbase=$BLOCK_SIGNER_ADDRESS \
-        --gcmode=$NODE_TYPE \
-        # --metrics \
-        # --metrics.influxdb \
-        # --metrics.influxdb.endpoint=http://influxdb:8086 \
-        # --metrics.influxdb.database=l2geth \
-        $@
+        if [ ! -d "$GETH_CHAINDATA_DIR" ]; then
+            echo "$GETH_CHAINDATA_DIR missing, running init"
+            geth init --datadir="$GETH_DATA_DIR" "$L2GETH_GENESIS_URL" "$L2GETH_GENESIS_HASH"
+            echo "geth init complete"
+        else
+            echo "$GETH_CHAINDATA_DIR exists, checking for hardfork."
+            echo "Chain config:"
+            geth dump-chain-cfg --datadir="$GETH_DATA_DIR"
+            if geth dump-chain-cfg --datadir="$GETH_DATA_DIR" | grep -q "\"berlinBlock\": $L2GETH_BERLIN_ACTIVATION_HEIGHT"; then
+                echo "Hardfork already activated."
+            else
+                echo "Hardfork not activated, running init."
+                geth init --datadir="$GETH_DATA_DIR" "$L2GETH_GENESIS_URL" "$L2GETH_GENESIS_HASH"
+                echo "geth hardfork activation complete"
+            fi
+        fi
+      l2geth-start.sh: |-
+        #!/bin/sh
+        set -eou
+        if [[ -z $DATADIR ]]; then
+            echo "Must pass DATADIR"
+            exit 1
+        fi
+        if [[ -z $BLOCK_SIGNER_ADDRESS ]]; then
+            echo "Must pass BLOCK_SIGNER_ADDRESS"
+            exit 1
+        fi
+        exec geth \
+          --vmodule=eth/*=5,miner=4,rpc=5,rollup=4,consensus/clique=1 \
+          --datadir=$DATADIR \
+          --password=$DATADIR/password \
+          --allow-insecure-unlock \
+          --unlock=$BLOCK_SIGNER_ADDRESS \
+          --mine \
+          --miner.etherbase=$BLOCK_SIGNER_ADDRESS \
+          --gcmode=$NODE_TYPE \
+          # --metrics \
+          # --metrics.influxdb \
+          # --metrics.influxdb.endpoint=http://influxdb:8086 \
+          # --metrics.influxdb.database=l2geth \
+          $@
 
   environment:
     ###############################################################################
